# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lab7_q2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lab7_q2
pod 'Kingfisher', '~> 5.0'


end
